%let rootpath=F:\16数学建模\2016赛题终\B\B题附件;
/*导入基因位点来源genotype.dat*/
data SNPs;
	infile "&rootpath.\genotype.dat" obs=1 lrecl=100000;
	informat name $20.;
	input name : @@;
	n=_n_;
run;
proc sql noprint;
	select name into :macsnps1 separated by ' ' from SNPs(where=(n le 5500));
quit;
proc sql noprint;
	select name into :macsnps2 separated by ' ' from SNPs(where=(n gt 5500));
quit;
data genotype;
	infile "&rootpath.\genotype.dat" firstobs=2 lrecl=100000;
	informat &macsnps1. &macsnps2. $20.;
	input &macsnps1. &macsnps2. : @@;
run;
/*导入健康情况，来源phenotype.txt*/
data phenotype;
	infile "&rootpath.\phenotype.txt"  lrecl=100000;
	informat health $20.;
	input health : @@;
	personid=_n_;
run;
/*合并*/
data sample;
	set phenotype;set genotype;
run;
proc sort data=sample;
	by personid health;
run;
proc transpose data=sample out=transample;
	var &macsnps1. &macsnps2.;
	by personid health;
run;
proc sort data=transample;
	by _name_;
run;
proc freq data=transample noprint;
	tables health*col1/out=a;
	by _name_;
run;
proc freq data=a noprint;
	tables health*col1/chisq measures norow nocol;
	weight count;
	by _name_;
	output out=b chisq;
run;
/*导入疾病情况来源multi_phenos.txt*/
data multi_phenos;
	infile "&rootpath.\multi_phenos.txt";
	input disease_1 - disease_10 $1.;
	personid=_n_;
run;
/*导入300基因与位点的相关情况*/
%macro getgene(datapath=);
	%if %sysfunc(exist(genelist)) %then %do;
		proc datasets lib=work noprint;
			delete genelist;
		quit;
	%end;
	%do i=1 %to 300;
		data tempgene;
			infile "&datapath.\gene_info\gene_&i..dat";
			input snps : $20.;
			format genename $10.;
			genename="gene_&i.";
			spns=cats('spns_',_n_);
		run;
		proc transpose data=tempgene out=templist(drop=_name_);
			by genename;
			id spns;
			var snps;
		run;
		%if %sysfunc(exist(genelist)) %then %do;
			data genelist;
				set genelist templist;
			run;
		%end;
		%else %do;
			data genelist;
				set templist;
			run;
		%end;
		proc datasets lib=work noprint;
			delete templist tempgene;
		quit;
	%end;
%mend getgene;
%getgene(datapath=&rootpath.);
options source notes;
%macro freq;
	%if %sysfunc(exist(chiresult)) %then %do;
		proc datasets lib=work noprint;
			delete chiresult;
		quit;
	%end;
	%do i=1 %to 20;
		%if &i. le 5500 %then %do;
			%let rvar=%scan(&macsnps1.,&i.,%str( ));
		%end;
		%else %do;
			%let rvar=%scan(&macsnps2.,%eval(&i.-5500),%str( ));
		%end;
		proc freq data=sample noprint;
			tables health*&rvar./out=a;
		run;
		proc freq data=a noprint;
			tables health*&rvar./chisq measures norow nocol;
			weight count;
			output out=b chisq;
		run;
		data b;
			format vname $20.;
			vname="&rvar.";
			set b;
		run;
		%if %sysfunc(exist(chiresult)) %then %do;
			data chiresult;
				set chiresult b;
			run;
		%end;
		%else %do;
			data chiresult;
				set b;
			run;
		%end;
	%end;
%mend freq;
%freq;
		proc freq data=sample;
			tables health*rs3094315/out=a;
		run;
		proc freq data=a;
			tables health*rs3094315/chisq measures norow nocol;
			weight count;
			output out=b CHISQ;
		run;
